// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BackgroundText: typeof import('C:/Projects/my-page/src/components/BackgroundText.vue')['default']
    BGTextItem: typeof import('C:/Projects/my-page/src/components/BGTextItem.vue')['default']
    'Bi:github': typeof import('~icons/bi/github')['default']
    'Bi:instagram': typeof import('~icons/bi/instagram')['default']
    'Bi:linkedin': typeof import('~icons/bi/linkedin')['default']
    'Bi:telegram': typeof import('~icons/bi/telegram')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('C:/Projects/my-page/src/components/Footer.vue')['default']
    Header: typeof import('C:/Projects/my-page/src/components/Header.vue')['default']
    'IconParkOutline:telegram': typeof import('~icons/icon-park-outline/telegram')['default']
    'Mdi:arrowRight': typeof import('~icons/mdi/arrow-right')['default']
    'Mdi:shareVariantOutline': typeof import('~icons/mdi/share-variant-outline')['default']
    NavBtn: typeof import('C:/Projects/my-page/src/components/NavBtn.vue')['default']
    'Octicon:shareAndroid16': typeof import('~icons/octicon/share-android16')['default']
    README: typeof import('C:/Projects/my-page/src/components/README.md')['default']
    Socials: typeof import('C:/Projects/my-page/src/components/Socials.vue')['default']
    TextBackground: typeof import('C:/Projects/my-page/src/components/textBackground.vue')['default']
  }
}

export { }
